apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pe-eng-transaction-processor-dev
  labels:
    app.kubernetes.io/name: transaction-processor
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pe-eng-transaction-processor-dev
  minReplicas: 5
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
