apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-transaction-processor-metrics-collector-secret
  labels:
    app.kubernetes.io/name: transaction-processor
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
type: Opaque
data:
  api-key: bWV0cmljcy1hcGkta2V5
  auth-token: bWV0cmljcy1hdXRoLXRva2Vu
