apiVersion: v1
kind: Secret
metadata:
  name: pe-eng-transaction-processor-db-shard-1-secret
  labels:
    app.kubernetes.io/name: transaction-processor
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
type: Opaque
data:
  username: ZGItc2hhcmQtMS11c2Vy
  password: ZGItc2hhcmQtMS1wYXNz
