apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-transaction-processor-db-shard-1-config
  labels:
    app.kubernetes.io/name: transaction-processor
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
data:
  host: "transaction-db-shard-1-hostname"
  port: "5432"
  database: "transaction_processor_shard_1"
  connection-params: "sslmode=require&application_name=transaction-processor"
  max-connections: "25"
  connection-timeout: "30"
  write-timeout: "3000"
  read-timeout: "1000"
