apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-transaction-processor-redis-cluster-config
  labels:
    app.kubernetes.io/name: transaction-processor
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
data:
  cluster-nodes: "redis-node1:6379,redis-node2:6379,redis-node3:6379"
  port: "6379"
  timeout: "5000"
  max-connections: "50"
  connection-timeout: "30"
