apiVersion: v1
kind: ConfigMap
metadata:
  name: pe-eng-transaction-processor-audit-service-config
  labels:
    app.kubernetes.io/name: transaction-processor
    app.kubernetes.io/version: "2.0.1"
    app.kubernetes.io/part-of: banking-platform
    environment: dev
    managed-by: helm
data:
  base-url: "https://audit-service.internal.banking.com"
  timeout: "15000"
  retry-config: "3"
  batch-size: "100"
  connection-timeout: "30"
